In [6]:
# Import libraries
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import os
import sys
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

from src.pre_post_loader import pre_post_reader,get_pre_post_difference

# Data Processing
## 1. Read data
- Data missing (40 uids)

In [7]:
data_path = '/Users/catherine/AI/UoA/T6/RA/code/StudentLife/data/dataset/survey/FlourishingScale.csv'
# Remove the row wtih NaN value
df, pre_df, post_df = pre_post_reader(data_path, mode='remove', to_int=True)

/Users/catherine/AI/UoA/T6/RA/code/StudentLife/src/pre_post_loader.py:31: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df[col_names[2:]] = new_df.loc[:, col_names[2:]].astype('int64')

In [8]:
pre_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 1 to 45
Data columns (total 10 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   uid                                                                    34 non-null     object
 1   type                                                                   34 non-null     object
 2   I lead a purposeful and meaningful life                                34 non-null     int64
 3   My social relationships are supportive and rewarding                   34 non-null     int64
 4   I am engaged and interested in my daily activities                     34 non-null     int64
 5   I actively contribute to the happiness and well-being of others        34 non-null     int64
 6   I am competent and capable in the activities that are important to me  34 non-null     int64
 7   I am a good person and live a good life                                34 non-null     int64
 8   I am optimistic about my future                                        34 non-null     int64
 9   People respect me                                                      34 non-null     int64
dtypes: int64(8), object(2)
memory usage: 2.9+ KB

In [9]:
post_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 34 entries, 47 to 82
Data columns (total 10 columns):
 #   Column                                                                 Non-Null Count  Dtype
---  ------                                                                 --------------  -----
 0   uid                                                                    34 non-null     object
 1   type                                                                   34 non-null     object
 2   I lead a purposeful and meaningful life                                34 non-null     int64
 3   My social relationships are supportive and rewarding                   34 non-null     int64
 4   I am engaged and interested in my daily activities                     34 non-null     int64
 5   I actively contribute to the happiness and well-being of others        34 non-null     int64
 6   I am competent and capable in the activities that are important to me  34 non-null     int64
 7   I am a good person and live a good life                                34 non-null     int64
 8   I am optimistic about my future                                        34 non-null     int64
 9   People respect me                                                      34 non-null     int64
dtypes: int64(8), object(2)
memory usage: 2.9+ KB

In [10]:
col_names = pre_df.columns[2:]
diff_df = get_pre_post_difference(pre_df, post_df,col_names,'flourishing')
diff_df

Check uid matching in the pre and post df: True

     flourishing_pre  flourishing_post  flourishing_delta
uid
u42               45                16                 29
u34               49                23                 26
u31               16                36                 20
u59               43                50                  7
u23               35                42                  7
u44               48                41                  7
u04               27                33                  6
u43               47                42                  5
u15               43                48                  5
u49               51                55                  4
u35               48                44                  4
u30               52                56                  4
u33               31                28                  3
u52               34                37                  3
u03               34                31                  3
u32               54                56                  2
u05               48                50                  2
u07               49                47                  2
u46               42                44                  2
u02               46                44                  2
u56               46                48                  2
u24               41                43                  2
u16               42                41                  1
u14               52                53                  1
u53               50                49                  1
u09               46                47                  1
u17               37                38                  1
u45               48                49                  1
u01               45                46                  1
u19               42                42                  0
u20               45                45                  0
u10               39                39                  0
u27               31                31                  0
u36               46                46                  0

In [12]:
# Replace the NaN value to 0
# df2, pre_df2, post_df2 = pre_post_reader(data_path, mode='replace', to_int=True)
# diff_df2 = get_difference(pre_df2,post_df2,col_names)
# diff_df2.head()